#let entry-list = (
  (
    key: "kuleuven",
    short: "KU Leuven",
    long: "Katholieke Universiteit Leuven",
    description: "A university in Belgium.", 
    group: "Acronyms"
  ),
  (key: "advi", short: "ADVI", long: "Automatic Differentiation Variational Inference", description: "", group: "Acronyms"),
(key: "aed", short: "AED", long: "Associative Experimental Design", description: "", group: "Acronyms"),
(key: "aic", short: "AIC", long: "Akaile Information Criterion", description: "", group: "Acronyms"),
(key: "ancova", short: "ANCOVA", long: "analysis of covariance", description: "", group: "Acronyms"),
(key: "anova", short: "ANOVA", long: "analysis of variance", description: "", group: "Acronyms"),
(key: "aws", short: "AWS", long: "Amazon.com Web Services", description: "", group: "Acronyms"),
(key: "bda", short: "BDA", long: "Bayesian data analysis", description: "", group: "Acronyms"),
(key: "best", short: "BEST", long: "Bayesian Estimation Supercedes the T-test", description: "", group: "Acronyms"),
(key: "bic", short: "BIC", long: "Bayesian Information Criterion", description: "", group: "Acronyms"),
(key: "bn", short: "BN", long: "Bayesian Network", description: "", group: "Acronyms"),
(key: "bp", short: "BP", long: "Belief Propagation", description: "", group: "Acronyms"),
(key: "bugs", short: "BUGS", long: "Bayesian inference Using Gibbs Sampling", description: "", group: "Acronyms"),
(key: "cli", short: "CLI", long: "Command Line Interface", description: "", group: "Acronyms"),
(key: "cmd", short: "CMD", long: "Conventional Model Discrimination", description: "", group: "Acronyms"),
(key: "cri", short: "CRI", long: "Credible Interval", description: "", group: "Acronyms"),
(key: "dbn", short: "DBN", long: "Dynamic Bayesian Network", description: "", group: "Acronyms"),
(key: "Ddic", short: "DIC", long: "Deviance Information Criterion", description: "", group: "Acronyms"),
(key: "doe", short: "DOE", long: "Design of Experiments", description: "", group: "Acronyms"),
(key: "eap", short: "EAP", long: "Expected a posterior", description: "", group: "Acronyms"),
(key: "ellgi", short: "eLLGI", long: "estimated Log-likelihood Gain on the Intensities", description: "", group: "Acronyms"),
(key: "em", short: "EM", long: "Expectation Maximization", description: "", group: "Acronyms"),
(key: "esda", short: "ESDA", long: "exploratory sequential data analysis", description: "", group: "Acronyms"),
(key: "ftp", short: "FTP", long: "File Transfer Protocol", description: "", group: "Acronyms"),
(key: "fortran", short: "FORTRAN", long: "FORMULA TRANSLATION", description: "", group: "Acronyms"),
(key: "ga", short: "GA", long: "Genetic Algorithm", description: "", group: "Acronyms"),
(key: "gam", short: "GAM", long: "Generalized Additive Models", description: "", group: "Acronyms"),
(key: "gee", short: "GEE", long: "Generalized Esimating Equations", description: "", group: "Acronyms"),
(key: "glm", short: "GLM", long: "General Linear Models", description: "", group: "Acronyms"),
(key: "glmm", short: "GLMM", long: "General Linear Mixed Models", description: "", group: "Acronyms"),
(key: "gmrf", short: "GMRF", long: "Gaussian Markov Random Field", description: "", group: "Acronyms"),
(key: "gmm", short: "GMM", long: "Generalized Methods of Moments", description: "", group: "Acronyms"),
(key: "gp", short: "GP", long: "Gaussian Processes", description: "", group: "Acronyms"),
(key: "gui", short: "GUI", long: "Graphical User Interface", description: "", group: "Acronyms"),
(key: "hci", short: "HCI", long: "Human-computer interactions", description: "", group: "Acronyms"),
(key: "hm", short: "HM", long: "Hierarchical Model", description: "", group: "Acronyms"),
(key: "hmc", short: "HMC", long: "Hamiltonian Monte Carlo or Hybrid MC", description: "", group: "Acronyms"),
(key: "hmm", short: "HMM", long: "Hidden Markov Model", description: "", group: "Acronyms"),
(key: "hpdi", short: "HPDI", long: "Highest Posterior Density Interval", description: "", group: "Acronyms"),
(key: "ife", short: "IFE", long: "Incomplete Factorial Experiments", description: "", group: "Acronyms"),
(key: "imse", short: "IMSE", long: "Integrated Mean Squared Error", description: "", group: "Acronyms"),
(key: "inla", short: "INLA", long: "Integrated Nested Laplace Approximation", description: "", group: "Acronyms"),
(key: "irls", short: "IRLS", long: "Iterative Re-Weighted Least-Squares", description: "", group: "Acronyms"),
(key: "iwls", short: "IWLS", long: "Iterative Weighted Least-Squares", description: "", group: "Acronyms"),
(key: "iw", short: "IW", long: "Inverse Wishart distribution", description: "", group: "Acronyms"),
(key: "jags", short: "JAGS", long: "Just Another Gibbs Sampler", description: "", group: "Acronyms"),
(key: "lasso", short: "LASSO", long: "least absobute shrinkage and selection operator", description: "", group: "Acronyms"),
(key: "l-bfgs", short: "L-BFGS", long: "limited-memory Broyden-Fletcher-Goldfarb-Shanno optimizer", description: "", group: "Acronyms"),
(key: "lm-bfgs", short: "LM-BFGS", long: "limited-memory Broyden-Fletcher-Goldfarb-Shanno optimizer", description: "", group: "Acronyms"),
(key: "lm", short: "LM", long: "Linear Models", description: "", group: "Acronyms"),
(key: "lmm", short: "LMM", long: "Linear Mixed Models", description: "", group: "Acronyms"),
(key: "lkj", short: "LKJ", long: "LKJ Distribution", description: "", group: "Acronyms"),
(key: "llgi", short: "LLGI", long: "log-likelihood Gain on the Intensities", description: "", group: "Acronyms"),
(key: "loo", short: "LOO", long: "Leave-One-Out", description: "", group: "Acronyms"),
(key: "lsf", short: "LSF", long: "Load Sharing Facility", description: "", group: "Acronyms"),
(key: "mala", short: "MALA", long: "Metropolis adjusted Langevin algorithms", description: "", group: "Acronyms"),
(key: "map", short: "MAP", long: "Maximum a posterior", description: "", group: "Acronyms"),
(key: "maxs", short: "MAXS", long: "Medium Angle X-ray Scattering", description: "", group: "Acronyms"),
(key: "mcem", short: "MCEM", long: "Monte Carlo Expectation Maximization", description: "", group: "Acronyms"),
(key: "mcmc", short: "MCMC", long: "Markov chain Monte Carlo", description: "", group: "Acronyms"),
(key: "ml", short: "ML", long: "Maximum Likelihood", description: "", group: "Acronyms"),
(key: "mle", short: "MLE", long: "Maximum Likelihood Estimate", description: "", group: "Acronyms"),
(key: "mrf", short: "MRF", long: "Markov Random Field", description: "", group: "Acronyms"),
(key: "mlirt", short: "MLIRT", long: "multilevel item response theory", description: "", group: "Acronyms"),
(key: "nb", short: "NB", long: "negative binomial", description: "", group: "Acronyms"),
(key: "nb1", short: "NB1", long: "negative binomial model 1", description: "", group: "Acronyms"),
(key: "nb2", short: "NB2", long: "negative binomial model 2", description: "", group: "Acronyms"),
(key: "nimble", short: "NIMBLE", long: "Numerical Inference Models Bayesian Likelihood Estimation", description: "", group: "Acronyms"),
(key: "nuts", short: "NUTS", long: "No U-Turn Sampler", description: "", group: "Acronyms"),
(key: "obsmd", short: "OBsMD", long: "Objective Bayesian Model Discrimination", description: "", group: "Acronyms"),
(key: "odbc", short: "ODBC", long: "Open Database Connectivity", description: "", group: "Acronyms"),
(key: "ols", short: "OLS", long: "Ordinary Least Squares", description: "", group: "Acronyms"),
(key: "omd", short: "OMD", long: "Objective Model Descrimination", description: "", group: "Acronyms"),
(key: "pb", short: "PB", long: "Plackett and Burman design", description: "", group: "Acronyms"),
(key: "pdf", short: "PDF", long: "Probability Density Function", description: "", group: "Acronyms"),
(key: "pddf", short: "PDDF", long: "Pairwise Distance Distribution Function (also P(r),),", description: "", group: "Acronyms"),
(key: "pdb", short: "PDB", long: "Protein Data Bank", description: "", group: "Acronyms"),
(key: "pMCMC", short: "pMCMC", long: "particle MCMC", description: "", group: "Acronyms"),
(key: "ppc", short: "PPC", long: "Posterior Predictive Checking", description: "", group: "Acronyms"),
(key: "ppl", short: "PPL", long: "Probabilistic Programming Language", description: "", group: "Acronyms"),
(key: "rmbms", short: "RDBMS", long: "relational database management system", description: "", group: "Acronyms"),
(key: "rest", short: "REST", long: "Representational State Transfer", description: "", group: "Acronyms"),
(key: "rmhmc", short: "RMHMC", long: "Riemannian manifold Hamiltonian Monte Carlo", description: "", group: "Acronyms"),
(key: "rj-mcmc", short: "RJ-MCMC", long: "Reverse Jump-MCMC", description: "", group: "Acronyms"),
(key: "rps", short: "RPS", long: "Rotational Pseudosymmetry", description: "", group: "Acronyms"),
(key: "rsm", short: "RSM", long: "Response Surface Methods", description: "", group: "Acronyms"),
(key: "saxs", short: "SAXS", long: "Small Angle X-ray Scattering", description: "", group: "Acronyms"),
(key: "sem", short: "SEM", long: "Structural Equation Modeling", description: "", group: "Acronyms"),
(key: "sfx", short: "SFX", long: "Serial Femtosecond Crystallography", description: "", group: "Acronyms"),
(key: "soap", short: "SOAP", long: "Simple Object Access Processing", description: "", group: "Acronyms"),
(key: "slurm", short: "SLURM", long: "Simple Linux Utility for Resource Management", description: "", group: "Acronyms"),
(key: "sms", short: "SMS", long: "Sparse Matrix Sampling", description: "", group: "Acronyms"),
(key: "smiles", short: "SMILES", long: "Simplified Molecular Input Line Entry System", description: "", group: "Acronyms"),
(key: "sql", short: "SQL", long: "Structured query language", description: "", group: "Acronyms"),
(key: "svm", short: "SVM", long: "support vector machine", description: "", group: "Acronyms"),
(key: "swaxs", short: "SWAXS", long: "Small and Wide Angle X-ray Scattering", description: "", group: "Acronyms"),
(key: "tps", short: "TPS", long: "Translational Pseudo Symmetry", description: "", group: "Acronyms"),
(key: "uml", short: "UML", long: "Unified Modeling Language", description: "", group: "Acronyms"),
(key: "vgam", short: "VGAM", long: "Vector Generalizer Additive Model", description: "", group: "Acronyms"),
(key: "vglm", short: "VGLM", long: "Vector Generalizer Linear Model", description: "", group: "Acronyms"),
(key: "waic", short: "WAIC", long: "Watanabe-Akaile Information Criterion", description: "", group: "Acronyms"),
(key: "waxs", short: "WAXS", long: "Wide Angle X-ray Scattering", description: "", group: "Acronyms"),
(key: "wsdl", short: "WSDL", long: "Web services description language", description: "", group: "Acronyms"),
(key: "xml", short: "XML", long: "Extensible Markup Language", description: "", group: "Acronyms"),
(key: "zinb", short: "ZINB", long: "Zero-Inflated Negative Binomial distribution", description: "", group: "Acronyms"),
(key: "zip", short: "ZIP", long: "Zero-Inflated Poisson distribution", description: "", group: "Acronyms"),
(key: "ztnb", short: "ZTNB", long: "Zero-Truncated Negative Binomial distribution", description: "", group: "Acronyms"),
(key: "ztp", short: "ZTP", long: "Zero-Truncated Poisson distribution", description: "", group: "Acronyms"),
    (
    key: "hci",
    short: "HCI",
    long: "Human-Computer Interactions",
    description: "Human-Computer Interaction (HCI) is a multidisciplinary field focused on the design and use of computer technology, emphasizing the interfaces between people (users) and computers. Researchers in HCI observe the ways humans interact with computers and design technologies that let humans interact with computers in novel ways. Key aspects of HCI include:
     1. Usability: Ensuring that computer systems are easy to use and efficient.
     2. User Experience (UX): Creating positive experiences for users through design.
     3. Accessibility: Making technology usable for people with a wide range of abilities.
     4. Interaction Design: Crafting the interactive aspects of a system, such as buttons, menus, and other controls.
     5. User-Centered Design: Involving users in the design process to ensure the product meets their needs.
    HCI combines principles from computer science, cognitive psychology, design, and several other fields to improve the interaction between users and computers.", 
    group: "Glossary"),

  // Add more terms
)
